### PR TITLE
1 soundcraft ui basic support

### LINKED ISSUE #1: Module Request: Soundcraft ui12 / ui16 / ui24
Remote-Control the ui series from soundcraft, a digital multichanel audiomixer

platform independent

I dont know about a API, but the mixer itself provides a html5 interface wich can be controlled with a standard browser. The mixer has a buildin W-LAN acesspoint and ethernet-port (RJ45)
https://www.soundcraft.com/en/products/ui16

Control the Mixer itself
Activate Mutegroups
Control the buildin Audioplayer (USB-Port)
... same usecases like the x32 from behringer / midas

### PR DESCRIPTION
**Pull request by TheMrPoseidon**
Resolves #1

### CODE REVIEW

**Comment by startmedia001** [comment]
@TheMrPoseidon Thank you so much for your effort in creating this module! Unfortunately I cant try it on my ui24 at the moment, but I will as soon as I can.

**Comment by TheMrPoseidon** [comment]
@startmedia001 No Problem. I'm really into feedback about if it is working on the ui24. I can't check it myself and as far as I know the the firmware for the ui24 is newer that for the ui12 und ui16.

**Comment by whizkidTRW** [comment]
I have a Soundcraft SI-Impact that I would love to control a few channels on from my Stream Deck. How can I try this?

**Comment by TheMrPoseidon** [comment]
@startmedia001 Hi, have you already tested it with the ui24?

**Comment by startmedia001** [comment]
> @startmedia001 Hi, have you already tested it with the ui24?

Hi @TheMrPoseidon unfortunately no. I have no access to the equipment from my usual rental company. They got hit badly by the lockdown in austria :-(

**Comment by TheMrPoseidon** [comment]
@startmedia001 Sorry to hear that. Wish you luck.

**Pull request merged**
